import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import{ThemeProvider,createTheme,CssBaseline,Box,AppBar,Toolbar,Typography,Button,Container,Paper,TextField,Stack,Alert,CircularProgress,Table,TableHead,TableRow,TableCell,TableBody,Chip,MenuItem,Dialog,DialogTitle,DialogContent,DialogActions,Drawer,List,ListItemButton,ListItemText,IconButton}from"@mui/material";
import{ConfirmationNumber,Logout,Refresh,Add,Dashboard,People,Category,Notifications}from"@mui/icons-material";
import{api,session,signIn,signOut}from"./api";
import "./style.css";
const theme=createTheme({palette:{primary:{main:"#245b8f"},background:{default:"#f4f7fb"}},shape:{borderRadius:10},typography:{fontFamily:"Inter, Roboto, Arial"}});
function App(){const[user,setUser]=useState(session.user),[view,setView]=useState("tickets"),[rows,setRows]=useState([]),[cats,setCats]=useState([]),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[notice,setNotice]=useState(""),[open,setOpen]=useState(false),[detail,setDetail]=useState(null),[comments,setComments]=useState([]),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[priority,setPriority]=useState("medium"),[status,setStatus]=useState(""),[comment,setComment]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState("");
async function load(){if(!user)return;setBusy(true);setErr("");try{if(view==="tickets"){const d=await api.get("/tickets?page=1&page_size=50");setRows(d.items||[])}else if(view==="categories")setRows(await api.get("/categories?active_only=false"));else if(view==="users"){const d=await api.get("/users?page=1&page_size=100");setRows(d.items||[])}else if(view==="notifications")setRows(await api.get("/notifications"));}catch(e){setErr(e.message)}finally{setBusy(false)}}
useEffect(()=>{load();},[view,user]);
async function login(e){e.preventDefault();setErr("");try{setUser(await signIn(email,password))}catch(e){setErr(e.message)}}
if(!user)return <Container maxWidth="sm"><Paper sx={{mt:12,p:4}}><Typography variant="h4" fontWeight={700} mb={1}>Support Desk</Typography><Typography color="text.secondary" mb={3}>Sign in to manage support requests.</Typography>{err&&<Alert severity="error" sx={{mb:2}}>{err}</Alert>}<Box component="form" onSubmit={login}><Stack spacing={2}><TextField label="Email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><TextField label="Password" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/><Button type="submit" variant="contained" size="large">Sign in</Button></Stack></Box></Paper></Container>;
async function openTicket(id){try{const [t,c]=await Promise.all([api.get(`/tickets/${id}`),api.get(`/comments/tickets/${id}`).catch(()=>[])]);setDetail(t);setComments(c||[]);setStatus(t.status);setOpen(true)}catch(e){setErr(e.message)}}
async function create(){try{await api.post("/tickets",{title,description,priority});setNotice("Ticket created");setTitle("");setDescription("");setView("tickets");load()}catch(e){setErr(e.message)}}
async function updateStatus(){try{await api.patch(`/tickets/${detail.id}/status`,{status});setNotice("Status updated");setOpen(false);load()}catch(e){setErr(e.message)}}
async function addComment(){try{await api.post(`/comments/tickets/${detail.id}`,{content:comment});setComment("");setComments(await api.get(`/comments/tickets/${detail.id}`));}catch(e){setErr(e.message)}}
const nav=[["tickets","Tickets",<ConfirmationNumber/>],["create","Create ticket",<Add/>],["categories","Categories",<Category/>],["users","Users",<People/>],["notifications","Notifications",<Notifications/>]];
return <Box><AppBar position="static"><Toolbar><Typography variant="h6" sx={{flexGrow:1,fontWeight:700}}>Support Desk</Typography><Typography sx={{mr:2}}>{user.name||user.email} · {user.role}</Typography><Button color="inherit" startIcon={<Logout/>} onClick={async()=>{await signOut();setUser(null)}}>Logout</Button></Toolbar></AppBar><Box sx={{display:"flex"}}><Drawer variant="permanent" sx={{width:220,flexShrink:0,"& .MuiDrawer-paper":{width:220,top:64,height:"calc(100% - 64px)",boxSizing:"border-box"}}}><List>{nav.filter(([v])=>v!=="users"||user.role==="admin").map(([v,n,i])=><ListItemButton selected={view===v} key={v} onClick={()=>setView(v)}>{i}<ListItemText sx={{ml:1}} primary={n}/></ListItemButton>)}</List></Drawer><Container sx={{py:4,minWidth:0}}><Stack direction="row" alignItems="center" justifyContent="space-between" mb={3}><Typography variant="h4" fontWeight={700}>{view==="create"?"Create ticket":view[0].toUpperCase()+view.slice(1)}</Typography><IconButton onClick={load}><Refresh/></IconButton></Stack>{err&&<Alert severity="error" sx={{mb:2}} onClose={()=>setErr("")}>{err}</Alert>}{notice&&<Alert severity="success" sx={{mb:2}} onClose={()=>setNotice("")}>{notice}</Alert>}
{view==="create"?<Paper sx={{p:3,maxWidth:700}}><Stack spacing={2}><TextField label="Title" value={title} onChange={e=>setTitle(e.target.value)} required/><TextField label="Description" multiline minRows={5} value={description} onChange={e=>setDescription(e.target.value)} required/><TextField select label="Priority" value={priority} onChange={e=>setPriority(e.target.value)}>{["low","medium","high","urgent"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><Button variant="contained" onClick={create} disabled={!title.trim()||!description.trim()}>Create ticket</Button></Stack></Paper>:busy?<CircularProgress/>:<Paper sx={{overflow:"auto"}}><Table><TableHead><TableRow>{(view==="tickets"?["Ticket","Title","Status","Priority","Created",""]:view==="users"?["Name","Email","Role"]:view==="categories"?["Category","Description","Status"]:["Notification","Details","Date"]).map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map((r,i)=><TableRow hover key={r.id||i}>{view==="tickets"?<><TableCell>{r.ticket_number||r.id}</TableCell><TableCell>{r.title}</TableCell><TableCell><Chip size="small" label={r.status}/></TableCell><TableCell>{r.priority}</TableCell><TableCell>{r.created_at?new Date(r.created_at).toLocaleString():"—"}</TableCell><TableCell><Button onClick={()=>openTicket(r.id)}>View</Button></TableCell></>:view==="users"?<><TableCell>{r.name}</TableCell><TableCell>{r.email}</TableCell><TableCell>{r.role}</TableCell></>:view==="categories"?<><TableCell>{r.name}</TableCell><TableCell>{r.description||"—"}</TableCell><TableCell>{String(r.is_active??r.active??"—")}</TableCell></>:<><TableCell>{r.title||r.message||"Notification"}</TableCell><TableCell>{r.message||r.content||"—"}</TableCell><TableCell>{r.created_at||"—"}</TableCell></>}</TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={6} align="center">No records found</TableCell></TableBody>}</TableBody></Table></Paper>}</Container></Box>
<Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>{detail?.ticket_number} · {detail?.title}</DialogTitle><DialogContent dividers><Typography sx={{whiteSpace:"pre-wrap",mb:2}}>{detail?.description}</Typography><Stack direction="row" spacing={2} alignItems="center" mb={2}><TextField select size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)}>{["open","in_progress","resolved","closed"].map(x=><MenuItem value={x} key={x}>{x}</MenuItem>)}</TextField><Button onClick={updateStatus} variant="contained">Update status</Button></Stack><Typography variant="h6">Comments</Typography>{comments.map(c=><Paper key={c.id} sx={{p:1.5,my:1}}>{c.content||c.body}<Typography variant="caption" display="block">{c.created_at||""}</Typography></Paper>)}<TextField fullWidth multiline minRows={2} label="Add comment" value={comment} onChange={e=>setComment(e.target.value)} sx={{mt:2}}/><Button sx={{mt:1}} onClick={addComment} disabled={!comment.trim()}>Post comment</Button></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Close</Button></DialogActions></Dialog></Box>}
createRoot(document.getElementById("root")).render(<ThemeProvider theme={theme}><CssBaseline/><App/></ThemeProvider>);
